### ISSUE TITLE
function address as value

### ISSUE THREAD

**Issue by niXman** [boost-ext/mph#1]
hello,

I'm just trying to change the [example](https://godbolt.org/z/fWY8YYeEE) to use function addresses as values, and I ran into an error saying that the values must be constexpr expressions: https://godbolt.org/z/qcb81Gjnv

I think I'm using MPH incorrectly =)

could you explain please?

best!

**Comment by krzysztof-jusiak** [comment]
Hi,

It depends what you are trying to achieve? mph only function is to map keys to values, so not sure how your example should work?

However, if you just wanna call red,green,blue functions maybe the following is closer to what you are after?

```
constexpr int red() { return 0; }
constexpr int green() { return 1; }
constexpr int blue() { return 2; }

int main() {
    constexpr auto colors = std::array{
        mph::pair{"red", 0},
        mph::pair{"green", 1},
        mph::pair{"blue", 2},
    };

    static_assert(0 == std::array{ red, green, blue }[*mph::hash<colors>("red")]());
    static_assert(1 == std::array{ red, green, blue }[*mph::hash<colors>("green")]());
    static_assert(2 == std::array{ red, green, blue }[*mph::hash<colors>("blue")]());
}

```

> https://godbolt.org/z/hY88aGbj4

**Comment by niXman** [comment]
hi,

I'm sorry, I didn't read the example carefully, the `colors` var is just an array =)

I'm researching the possibility to use direct addressing of an array of function pointers.
now the task is implemented using binary search through a sorted array of pairs: `{fnv1a(function_name_str), function_pointer}`

**Comment by krzysztof-jusiak** [comment]
Good luck! Interested to see your finding. Feel free to raise any more issues/questions.
